export default {
  layoutContent: {
    flex: 1,
    alignItems: 'center',
  },
  bgCover: {
    flex: 1,
    backgroundColor: 'rgba(102, 153, 255,0.8)',
  },
  section: {
    width: '100%',
    paddingHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    marginTop: 50,
    marginBottom: 20,
  },
  signBg: {
    width: '100%',
    height: 200,
    justifyContent: 'space-between',
    backgroundColor: '#FFF',
    borderRadius: 8,
    elevation: 10,
    shadowOffset: {
      width: 15,
      height: 15,
    },
    shadowColor: 'grey',
    shadowOpacity: 0.1,
    shadowRadius: 0,
  },
  col: {
    flexDirection: 'row',
  },
  textInput: {
    //fontFamily: 'Montserrat-Regular',
    borderBottomWidth: 1,
    borderColor: '#DDD',
    paddingHorizontal: 20,
    paddingVertical: 15,
    fontSize: 13,
    width: '100%',
  },
  textInputHalf: {
    //fontFamily: 'Montserrat-Regular',
    borderBottomWidth: 1,
    borderColor: '#DDD',
    paddingHorizontal: 20,
    paddingVertical: 15,
    fontSize: 12,
    width: '50%',
  },
  btn: {
    width: '100%',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#FCC300',
    paddingVertical: 20,
    paddingHorizontal: 5,
  },
  btnText: {
    //fontFamily: 'Montserrat-SemiBold',
    color: '#333',
    fontSize: 14,
    alignSelf: 'center',
    fontWeight: '700',
  },

  loginBtnText: {
    //fontFamily: 'Montserrat-SemiBold',
    color: '#333',
    fontSize: 12,
  },
  loginBtnIcon: {
    color: '#333',
    fontSize: 24,
  },

  login: {
    flex: 1,
    marginVertical: 30,
    width: '100%',
    alignItems: 'center',
  },
  account: {
    //fontFamily: 'Montserrat-Regular',
    color: '#FFF',
    fontSize: 12,
  },
  btnLogin: {
    //fontFamily: 'Montserrat-Regular',
    color: '#FFF',
    fontSize: 14,
    justifyContent: 'center',
    flex: 1,
    height: 40,
    padding: 5,
    textAlign: 'center',
  },
  forgot: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  btnForgot: {
    //fontFamily: 'Montserrat-Regular',
    color: '#FFF',
    paddingVertical: 15,
    textAlign: 'right',
    fontSize: 13,
  },
  logoContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'flex-end',
  },
  divider: {
    width: 5,
  },
  btns: {
    backgroundColor: 'rgb(0, 102, 255)',
    flex: 1,
    height: 70,
    marginBottom: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTexts: {
    color: '#fff',
    fontSize: 20,
  },
  appName: {
    color: '#fff',
    fontSize: 50,
    fontWeight: 'bold',
  },
  appSloganContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appSlogan: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
  },
};
